# Generated by Django 2.1 on 2018-08-14 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.TextField(default='None', max_length=50, null=True)),
                ('title', models.CharField(default='Not Created', max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_time', models.DateTimeField(null=True)),
                ('assistant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('type', models.TextField(max_length=50)),
                ('intro', models.TextField(max_length=5000, null=True)),
                ('abstract', models.TextField(max_length=5000, null=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('review_status', models.TextField(default='Not Reviewed', max_length=20)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('accept_status', models.TextField(default='Not Accepted', max_length=20)),
                ('accept_date', models.DateTimeField(blank=True, null=True)),
                ('document', models.FileField(null=True, upload_to='documents/')),
                ('document_upload_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tag')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='Tag')),
                ('last_modified_time', models.DateField(auto_now=True, verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='tags',
            field=models.ManyToManyField(to='MonashIE.Tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='quest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='MonashIE.Quest'),
        ),
    ]
